const initialState = {
  trendingMovies: [
    {
      popularity: 78.869,
      vote_count: 17380,
      video: false,
      poster_path: "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
      id: 671,
      adult: false,
      backdrop_path: "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
      original_language: "en",
      original_title: "Harry Potter and the Philosopher's Stone",
      genre_ids: [12, 14, 10751],
      title: "Harry Potter and the Philosopher's Stone",
      vote_average: 7.9,
      overview:
        "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths -- and about the villain who's to blame.",
      release_date: "2001-11-16",
    },
    {
      popularity: 48.229,
      vote_count: 14503,
      video: false,
      poster_path: "/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
      id: 672,
      adult: false,
      backdrop_path: "/bvRnPaai6JL7XHF4K6414DdSHro.jpg",
      original_language: "en",
      original_title: "Harry Potter and the Chamber of Secrets",
      genre_ids: [12, 14],
      title: "Harry Potter and the Chamber of Secrets",
      vote_average: 7.7,
      overview:
        "Cars fly, trees fight back, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry, Ron and Hermione’s magical abilities and courage.",
      release_date: "2002-11-13",
    },
    {
      popularity: 40.659,
      id: 767,
      video: false,
      vote_count: 12847,
      vote_average: 7.7,
      title: "Harry Potter and the Half-Blood Prince",
      release_date: "2009-07-07",
      original_language: "en",
      original_title: "Harry Potter and the Half-Blood Prince",
      genre_ids: [12, 14],
      backdrop_path: "/kT8bDEAgEYBKhRJtqM97qTw6uRW.jpg",
      adult: false,
      overview:
        "As Harry begins his sixth year at Hogwarts, he discovers an old book marked as 'Property of the Half-Blood Prince', and begins to learn more about Lord Voldemort's dark past.",
      poster_path: "/Ag21otqbeynZPGjEbzyr3X5Us0j.jpg",
    },
    {
      popularity: 32.194,
      vote_count: 14135,
      video: false,
      poster_path: "/uDQibffYgssdiqx7izO57wdLc6.jpg",
      id: 673,
      adult: false,
      backdrop_path: "/vbk5CfaAHOjQPSAcYm6AoRRz2Af.jpg",
      original_language: "en",
      original_title: "Harry Potter and the Prisoner of Azkaban",
      genre_ids: [12, 14],
      title: "Harry Potter and the Prisoner of Azkaban",
      vote_average: 8,
      overview:
        "Harry, Ron and Hermione return to Hogwarts for another magic-filled year. Harry comes face to face with danger yet again, this time in the form of escaped convict, Sirius Black—and turns to sympathetic Professor Lupin for help.",
      release_date: "2004-05-31",
    },
    {
      popularity: 25.68,
      vote_count: 13538,
      video: false,
      poster_path: "/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg",
      id: 674,
      adult: false,
      backdrop_path: "/8f9dnOtpArDrOMEylpSN9Sc6fuz.jpg",
      original_language: "en",
      original_title: "Harry Potter and the Goblet of Fire",
      genre_ids: [12, 14, 10751],
      title: "Harry Potter and the Goblet of Fire",
      vote_average: 7.8,
      overview:
        "Harry starts his fourth year at Hogwarts, competes in the treacherous Triwizard Tournament and faces the evil Lord Voldemort. Ron and Hermione help Harry manage the pressure – but Voldemort lurks, awaiting his chance to destroy Harry and all that he stands for.",
      release_date: "2005-11-16",
    },
    {
      popularity: 33.153,
      vote_count: 13965,
      video: false,
      poster_path: "/da22ZBmrDOXOCDRvr8Gic8ldhv4.jpg",
      id: 12445,
      adult: false,
      backdrop_path: "/n5A7brJCjejceZmHyujwUTVgQNC.jpg",
      original_language: "en",
      original_title: "Harry Potter and the Deathly Hallows: Part 2",
      genre_ids: [12, 14],
      title: "Harry Potter and the Deathly Hallows: Part 2",
      vote_average: 8.1,
      overview:
        "Harry, Ron and Hermione continue their quest to vanquish the evil Voldemort once and for all. Just as things begin to look hopeless for the young wizards, Harry discovers a trio of magical objects that endow him with powers to rival Voldemort's formidable skills.",
      release_date: "2011-07-07",
    },
    {
      popularity: 32.177,
      vote_count: 13147,
      video: false,
      poster_path: "/g6n8G0xPnBVUIKKK41sNmbZB5h4.jpg",
      id: 675,
      adult: false,
      backdrop_path: "/pkxPkHOPJjOvzfQOclANEBT8OfK.jpg",
      original_language: "en",
      original_title: "Harry Potter and the Order of the Phoenix",
      genre_ids: [12, 14, 9648],
      title: "Harry Potter and the Order of the Phoenix",
      vote_average: 7.7,
      overview:
        "Returning for his fifth year of study at Hogwarts, Harry is stunned to find that his warnings about the return of Lord Voldemort have been ignored. Left with no choice, Harry takes matters into his own hands, training a small group of students – dubbed 'Dumbledore's Army' – to defend themselves against the dark arts.",
      release_date: "2007-06-28",
    },
    {
      popularity: 27.451,
      vote_count: 12998,
      video: false,
      poster_path: "/iGoXIpQb7Pot00EEdwpwPajheZ5.jpg",
      id: 12444,
      adult: false,
      backdrop_path: "/fXRXpzxUApE3OuXhIqsdavQjCVa.jpg",
      original_language: "en",
      original_title: "Harry Potter and the Deathly Hallows: Part 1",
      genre_ids: [12, 14],
      title: "Harry Potter and the Deathly Hallows: Part 1",
      vote_average: 7.8,
      overview:
        "Harry, Ron and Hermione walk away from their last year at Hogwarts to find and destroy the remaining Horcruxes, putting an end to Voldemort's bid for immortality. But with Harry's beloved Dumbledore dead and Voldemort's unscrupulous Death Eaters on the loose, the world is more dangerous than ever.",
      release_date: "2010-10-17",
    },
    {
      popularity: 6.983,
      vote_count: 19,
      video: false,
      poster_path: "/peJehrEiA5xD9sFBuL61MQdFY0n.jpg",
      id: 482408,
      adult: false,
      backdrop_path: "/mjCYpJXCBYDZgMr1U1KZcFgFDfC.jpg",
      original_language: "en",
      original_title: "Harry Potter - A History Of Magic",
      genre_ids: [99],
      title: "Harry Potter - A History Of Magic",
      vote_average: 7,
      overview:
        "A thrilling journey through legends, belief and folklore, this film goes behind the scenes with the British Library as they search to tell that story through objects in their collection, in an ambitious new exhibition: Harry Potter: A History Of Magic.  J.K. Rowling, who is lending unseen manuscripts, drawings and drafts from her private archives (which will sit alongside treasures from the British Library, as well as original drafts and drawings from Jim Kay) talks about some of the personal items she has lent to the exhibition and gives new insight into her writing, looking at some of the objects from the exhibition that have fired her imagination.",
      release_date: "2017-10-28",
    },
    {
      popularity: 6.198,
      vote_count: 8,
      video: false,
      poster_path: "/g1xiBoLD6v3ZaXPa4QtuXiQeYKW.jpg",
      id: 483898,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "50 Greatest Harry Potter Moments",
      genre_ids: [99],
      title: "50 Greatest Harry Potter Moments",
      vote_average: 8.4,
      overview:
        "To mark the release two weeks ago of the eighth and final movie in the series, Robbie Coltrane narrates a countdown of the movie franchise's best moments. From Harry's first meeting with Ron and Hermione aboard the Hogwarts Express through to magical mysteries.",
      release_date: "2011-07-27",
    },
    {
      popularity: 5.193,
      vote_count: 5,
      video: false,
      poster_path: "/yLpnOqKw3ZycFu8t5Gil1BqTbnB.jpg",
      id: 116972,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "Discovering the Real World of Harry Potter",
      genre_ids: [99, 10751],
      title: "Discovering the Real World of Harry Potter",
      vote_average: 6,
      overview:
        "Explore the myths and legends that inhabit the real world of Harry Potter. Follow award-winning documentary filmmakers as they offer insights to witches, wizards, Greek gods, ancient Celts, ghosts, magical creatures, alchemy, and ancient spells. Narrated by British actor Hugh Laurie, this fascinating documentary brings new dimensions to the historical and scientific world behind the Harry Potter series.",
      release_date: "2001-12-10",
    },
    {
      popularity: 1.41,
      id: 341415,
      video: false,
      vote_count: 2,
      vote_average: 10,
      title: "'Harry Potter': Behind the Magic",
      release_date: "2005-11-19",
      original_language: "en",
      original_title: "'Harry Potter': Behind the Magic",
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        "DVD that came with special box set. Covers the making of Harry Potter and the Goblet of Fire (2005).",
      poster_path: null,
    },
    {
      popularity: 1.4,
      vote_count: 0,
      video: false,
      poster_path: "/pW2R67fLa6swhTbnydoln66w25X.jpg",
      id: 719020,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "I Am Harry Potter",
      genre_ids: [],
      title: "I Am Harry Potter",
      vote_average: 0,
      overview:
        "The Boy Who Lived. The Chosen One. But no class at Hogwarts could have prepared Harry Potter for this next chapter in his amazing story. Harry is back in the Muggle world, and trying his hand at acting. Soon Harry is taking on his most challenging role ever as Daniel Radcliffe.",
      release_date: "",
    },
    {
      popularity: 1.758,
      vote_count: 2,
      video: false,
      poster_path: null,
      id: 109004,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "The Seeker's Guide to Harry Potter",
      genre_ids: [99],
      title: "The Seeker's Guide to Harry Potter",
      vote_average: 5.3,
      overview:
        "In this documentary, Dr. Geo Trevarthen uses psychology, theology and other disciplines to explore the mystical world of J.K. Rowling's Harry Potter novels, giving fans a deeper appreciation for the symbolism and magic in the books. Looking at the entire series, Trevarthen pays special attention to how readers' lives may intersect with shamanism and other real-world mystical traditions that echo through the halls of Hogwarts.",
      release_date: "2010-11-23",
    },
    {
      popularity: 1.088,
      vote_count: 4,
      video: false,
      poster_path: null,
      id: 430481,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "Harry Potter: Witchcraft Repackaged",
      genre_ids: [99],
      title: "Harry Potter: Witchcraft Repackaged",
      vote_average: 5.5,
      overview:
        "Does Witchcraft/Wicca actually have power? If so, what is it's source? Does the Harry Potter series ' presentation of child-friendly Witchcraft make it's philosophy any more acceptable just because it is packaged as \"children's fantasy literature\"?",
      release_date: "2001-01-01",
    },
    {
      popularity: 0.6,
      vote_count: 0,
      video: false,
      poster_path: null,
      id: 697495,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "R-Rated Harry Potter",
      genre_ids: [16, 35, 14, 27],
      title: "R-Rated Harry Potter",
      vote_average: 0,
      overview:
        "An inappropriate spoof of Harry Potter and the Philosopher's Stone.",
      release_date: "2015-06-15",
    },
    {
      popularity: 3.58,
      vote_count: 0,
      video: false,
      poster_path: "/qlga5Wz89wdju6YkpeSr4mKatRi.jpg",
      id: 719646,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title:
        "Creating the World of Harry Potter, Part 4: Sound and Music",
      genre_ids: [99],
      title: "Creating the World of Harry Potter, Part 4: Sound and Music",
      vote_average: 0,
      overview:
        "Fourth part of the special documentaries about the Harry Potter Films, focusing in the sound and music of the series.",
      release_date: "2010-10-19",
    },
    {
      popularity: 2.018,
      id: 719644,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "Creating the World of Harry Potter, Part 2: Characters",
      release_date: "2009-11-17",
      original_language: "en",
      original_title: "Creating the World of Harry Potter, Part 2: Characters",
      genre_ids: [99],
      backdrop_path: null,
      adult: false,
      overview:
        "Dive deeper into the World of Harry Potter by focusing on the characters in the film and going behind the scenes with filmmakers.",
      poster_path: "/nQXuF3hrt0mn6YssvFV83KeNgP5.jpg",
    },
    {
      popularity: 0.783,
      id: 570724,
      video: false,
      vote_count: 3,
      vote_average: 10,
      title: "The Story of Harry Potter",
      release_date: "2018-12-24",
      original_language: "en",
      original_title: "The Story of Harry Potter",
      genre_ids: [99],
      backdrop_path: "/tlV4MEmntnKy9Mh46tB1TxBEc46.jpg",
      adult: false,
      overview:
        "A three-part documentary series by Mikey Neumann exploring the behind-the-scenes stories of the eight core Harry Potter films, as well as deconstructing their themes and messages.",
      poster_path: "/s0FRUpp9nsM0N8F2S7hdIgeAkHy.jpg",
    },
    {
      popularity: 0.875,
      id: 393135,
      video: false,
      vote_count: 1,
      vote_average: 10,
      title: "Harry Potter and the Ten Years Later",
      release_date: "2012-10-07",
      original_language: "en",
      original_title: "Harry Potter and the Ten Years Later",
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        "Furious Molecules' new parody web series 'Harry Potter and the Ten Years Later' takes a look at our hero ten years after taking down He-Whose-Name-Nobody-Quite-Remembers (but before that sappy epilogue full of kids). Things have changed significantly in Harry's world. With no dark wizards or witches left, the Ministry of Magic's Auror Department shuts down, leaving Harry unemployed. Ginny wants to start a family, Hermione is having doubts about her goody-goody lifestyle, and Ron... well, he's Ron. Everything seems very average in a late-twenties-problem kind of way-- but as always, trouble finds Harry yet again.",
      poster_path: "/zh1KtXxbcfj3wj202aEEE2E8V3n.jpg",
    },
  ],
  favoriteMovies: [],
  resultMovies: [],
};

const movieReducer = (state = initialState, action) => {
  switch (action.type) {
    default:
      return state;
  }
};

export default movieReducer;
