export const SET_UPDATE_TRENDING = "SET_UPDATE_TRENDING";
export const SET_UPDATE_FAVORITES = "SET_UPDATE_FAVORITES";
export const SET_DELETE_FAVORITES = "SET_DELETE_FAVORITES";
export const SET_RESULTS = "SET_RESULTS";
export const SET_ADD_TRENDING = "SET_ADD_TRENDING";
export const SET_REMOVE_TRENDING = "SET_REMOVE_TRENDING";
export const SET_SEARCH_LOADING = "SET_SEARCH_LOADING";
export const SET_REFRESH_STATE = "SET_REFRESH_STATE";
