const initialState = {
  trendingMovies: [
    {
      popularity: 3.728,
      id: 582808,
      video: false,
      vote_count: 1,
      vote_average: 5,
      title: "James Bond - 50th Anniversary: Bonus Features",
      release_date: "2012-01-01",
      original_language: "en",
      original_title: "James Bond - 50th Anniversary: Bonus Features",
      genre_ids: [28, 12, 10752],
      backdrop_path: null,
      adult: false,
      overview:
        "All the Bonds. All the girls. All the action. All in high-definition. Metro-Goldwyn-Mayer Studios and Twentieth Century Fox Home Entertainment mark James Bond’s monumental golden anniversary with the release of BOND 50, showcasing 22 of the classic Bond films on Blu-ray together for the first time ever, neatly packaged into one cool, sleek collectable box-set. The collection marks the debut of nine James Bond films previously unavailable in high definition Blu-ray and comes with a dossier of more than 122 hours of bonus features.",
      poster_path: "/fu5O6WNC1Dg3Nsd7l8VskNTxr9y.jpg",
    },
    {
      popularity: 2.315,
      vote_count: 10,
      video: false,
      poster_path: "/wG1iksqapNCNNZuIneHuF6j9Sg0.jpg",
      id: 44650,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "The James Bond Story",
      genre_ids: [99],
      title: "The James Bond Story",
      vote_average: 6.6,
      overview:
        "Bond... James Bond! Perhaps the greatest fictional cinema icon ever. He first appeared on the big screen in 1962 in Dr. No and has remained the most powerful action hero ever since. The secret to his success is his adaptability. No matter what tight spots he finds himself in, he always appears to be suave, sophisticated and cool. This is the full story -- from the creation of the character, the men who played him, all the toys, and all the women. Everything you wanted to know about James Bond... and more.",
      release_date: "1999-10-09",
    },
    {
      popularity: 2.325,
      vote_count: 2,
      video: false,
      poster_path: null,
      id: 264017,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "30 Years of James Bond",
      genre_ids: [99],
      title: "30 Years of James Bond",
      vote_average: 5.5,
      overview:
        "An examination of why the James Bond films have proved so popular including a discussion between the four actors who have played Bond, an interview with Cubby Broccoli and contributions from the directors, production designers, special effects and stuntmen.",
      release_date: "1992-10-03",
    },
    {
      popularity: 3.813,
      vote_count: 2,
      video: false,
      poster_path: "/mVeyZnJBNXFX6C02Hya1ZahH3xH.jpg",
      id: 368155,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "Happy Anniversary 007: 25 Years of James Bond",
      genre_ids: [99],
      title: "Happy Anniversary 007: 25 Years of James Bond",
      vote_average: 5.5,
      overview:
        "An hour documentary on the history of Bond for the 25th anniversary of the film series.",
      release_date: "1987-05-13",
    },
    {
      popularity: 1.744,
      vote_count: 3,
      video: false,
      poster_path: null,
      id: 147532,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "Noi non siamo come James Bond",
      genre_ids: [],
      title: "We're Nothing Like James Bond",
      vote_average: 7,
      overview:
        "How two friends, thanks to the strong relationship between them, piece back together the fragments of their existence sent topsy-turvy by serious illness? Through a peculiar kind of road movie, alternating the dense reflections of the two main characters on life, with their easy positive glances towards the future. Starting from a weird juvenile infatuation with James Bond: he utterly immortal, they extremely mortal. Now more than before.",
      release_date: "2012-11-29",
    },
    {
      popularity: 1.057,
      vote_count: 3,
      video: false,
      poster_path: "/kgeAS28rBZJSEVypaKpEaI4wunn.jpg",
      id: 266315,
      adult: false,
      backdrop_path: "/3zpR0XaPfXxmoh7inMDuim2Uc3S.jpg",
      original_language: "pa",
      original_title: "Jatt James Bond",
      genre_ids: [35, 18, 53],
      title: "Jatt James Bond",
      vote_average: 4,
      overview:
        "Shinda was mistreated by his relatives therefore he finds other ways to have his love Laali. Shinda and his two other friends come up with a plan to solve all of their problems.",
      release_date: "2014-04-25",
    },
    {
      popularity: 0.84,
      id: 433250,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "James Bond 777",
      release_date: "1971-01-01",
      original_language: "hi",
      original_title: "James Bond 777",
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        'The adventures of Kishore, a "James Bond 777" CBI agent, as he and heroine Sopa battle criminal mastermind "Boss" and his gang which includes whip-cracking Jamilla and a trio of highly trained dogs.',
      poster_path: "/bjRcdYNo7DX0WPegTAAvZAxKtPu.jpg",
    },
    {
      popularity: 0.709,
      vote_count: 2,
      video: false,
      poster_path: "/j523NJfe7KRUfBLSOPsGxrTgoyR.jpg",
      id: 688656,
      adult: false,
      backdrop_path: "/xptBI2iwXQWS3G9v1yfNKJX6Cag.jpg",
      original_language: "de",
      original_title: "Richard Sorge - Stalins James Bond",
      genre_ids: [99, 36, 10770],
      title: "Stalin's James Bond",
      vote_average: 6,
      overview:
        "An account of the troubled life of Richard Sorge (1895-1944), a Soviet spy of German origin who played a decisive role in the outcome of World War II.",
      release_date: "2017-12-30",
    },
    {
      popularity: 1.4,
      id: 465739,
      video: false,
      vote_count: 2,
      vote_average: 6,
      title: "James Bond Supports International Women's Day",
      release_date: "2011-03-05",
      original_language: "en",
      original_title: "James Bond Supports International Women's Day",
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        "This short film is made by 'We Are Equals' to celebrate International Women's Day. James Bond video for international women's day shows 007's feminine side. Daniel Craig and Dame Judi Dench team up for two-minute film highlighting the need for gender equality. 007 star Daniel Craig undergo a dramatic makeover as he puts himself, quite literally, in a woman's shoes.",
      poster_path: "/oiBCjrSexJd9O51KJtuWeMxSN8O.jpg",
    },
    {
      popularity: 0.87,
      vote_count: 1,
      video: false,
      poster_path: "/lCiDDPJyeM9NdQ7XQwMEkHamxBk.jpg",
      id: 252359,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "James Bond In India",
      genre_ids: [99],
      title: "James Bond In India",
      vote_average: 5,
      overview:
        "The making of the James Bond movie Octopussy (1983) in Udaipur, India during 1982.",
      release_date: "1983-01-25",
    },
    {
      popularity: 0.682,
      vote_count: 3,
      video: true,
      poster_path: null,
      id: 338749,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "James Bond: For Real",
      genre_ids: [99],
      title: "James Bond: For Real",
      vote_average: 7.7,
      overview:
        "The stunts and action set pieces for the the 2006 James Bond adventure 'Casino Royale'.",
      release_date: "2006-11-22",
    },
    {
      popularity: 0.731,
      vote_count: 3,
      video: false,
      poster_path: "/9YJVDUPQmQnHbl8S4UNbTDZDyU7.jpg",
      id: 209912,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "Silhouettes: The James Bond Titles",
      genre_ids: [99],
      title: "Silhouettes: The James Bond Titles",
      vote_average: 5.3,
      overview:
        "Documentary exploring the famous title sequences used in the Bond movies. Narrated by Patrick Macnee. Included on the 'You Only Live Twice' Bluray disc",
      release_date: "2000-07-25",
    },
    {
      popularity: 1.55,
      vote_count: 1,
      video: false,
      poster_path: "/d416YCqX42GzWaX6uzRe8iCnGtd.jpg",
      id: 264022,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "In Search of James Bond with Jonathan Ross",
      genre_ids: [99],
      title: "In Search of James Bond with Jonathan Ross",
      vote_average: 2,
      overview:
        "Jonathan Ross delves into the world of James Bond and meets with new and former cast members who reveal humorous stories and anecdotes in a series of interviews. All the 5 Bonds at the time are featured, though only Lazenby (reflecting in the usual frank, self criticizing manner), Moore and Brosnan granted an interview. Connery and Dalton are featured through some unused footage from LWT's 30 years of James Bond program. The ever faithful Desmond Llewelyn turns up in character as well as some other less related peeps like Christopher Lee, Paul McCartney and the ultimate playboy: Hugh Hefner -- who all give an interesting perspective on the worlds most famous spy.",
      release_date: "1995-12-10",
    },
    {
      popularity: 0.6,
      id: 368235,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "James Bond: License to Thrill",
      release_date: "",
      original_language: "en",
      original_title: "James Bond: License to Thrill",
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        "Promotional documentary television special celebrating the 25th Anniversary of James Bond and release of the then new James Bond film _Living Daylights, The (1987)_.",
      poster_path: null,
    },
    {
      popularity: 0.6,
      id: 538060,
      video: false,
      vote_count: 2,
      vote_average: 6,
      title: "The Guns of James Bond",
      release_date: "1964-01-01",
      original_language: "en",
      original_title: "The Guns of James Bond",
      genre_ids: [99],
      backdrop_path: null,
      adult: false,
      overview:
        "Short 1964 black-and-white documentary featurette hosted by Sean Connery and featuring the real-life inspiration for the character of Q, Major Geoffrey Boothroyd with a discussion of the gun weaponry used by James Bond.",
      poster_path: null,
    },
    {
      popularity: 0.6,
      id: 685325,
      video: true,
      vote_count: 0,
      vote_average: 0,
      title: "The World of James Bond",
      release_date: "",
      original_language: "en",
      original_title: "The World of James Bond",
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        "Elizabeth Hurley hosts a one hour documentary on the history of the James Bond film series to tie in with the seventeenth Bond film, GoldenEye.",
      poster_path: "/qlWcj1XNfvUQ3npoTrkmNdYPrAX.jpg",
    },
    {
      popularity: 0.628,
      vote_count: 1,
      video: false,
      poster_path: null,
      id: 332654,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "James Bond: In Service of Nothing",
      genre_ids: [28, 16],
      title: "James Bond: In Service of Nothing",
      vote_average: 7,
      overview:
        "An aging former super spy struggles to find his place in a self absorbed world without boarders, where service to one's nation is an antiquated concept.",
      release_date: "2015-03-02",
    },
    {
      popularity: 0.626,
      id: 508744,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "James Bond: The First 21 Years",
      release_date: "1983-05-27",
      original_language: "de",
      original_title: "James Bond: The First 21 Years",
      genre_ids: [99, 10770],
      backdrop_path: null,
      adult: false,
      overview: "",
      poster_path: "/i27tAbaQBSNMWzcv8QCwfMCxmkz.jpg",
    },
    {
      popularity: 0.6,
      id: 389491,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "James Bond 50th Anniversary Gala Concert",
      release_date: "2012-12-14",
      original_language: "en",
      original_title: "James Bond 50th Anniversary Gala Concert",
      genre_ids: [],
      backdrop_path: "/yzvifxX9OMlFGG11YYjaDNR95xq.jpg",
      adult: false,
      overview:
        "In 2012, to celebrate 50 years of James Bond films, the BBC broadcast a concert from the Royal Festival Hall in London celebrating the themes from Bond films over the years.",
      poster_path: "/iXREUxR8SAPihjoGVKsQ3VVQGKr.jpg",
    },
    {
      popularity: 0.6,
      id: 696912,
      video: false,
      vote_count: 1,
      vote_average: 6,
      title: "The Incredible World of James Bond",
      release_date: "1965-11-26",
      original_language: "en",
      original_title: "The Incredible World of James Bond",
      genre_ids: [99],
      backdrop_path: null,
      adult: false,
      overview:
        "This promotional film was aired on American television on 26 November 1965, one month before the release of Thunderball (1965). Narrated by Alexander Scourby, the 48 minute documentary aired as a one hour special. It included footage of the filming at Silverstone Racetrack, Northamptonshire and of the fight aboard the Disco Volante at Pinewood Studios; media coverage of Martine Beswick, Luciana Paluzzi and Claudine Auger; and archive footage of Ian Fleming at 'Goldeneye', Jamaica.",
      poster_path: null,
    },
  ],
  favoriteMovies: [],
  resultMovies: [],
};

const movieReducer = (state = initialState, action) => {
  switch (action.type) {
    default:
      return state;
  }
};

export default movieReducer;
